<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Banking</name>
   <tag></tag>
   <elementGuidId>eac4aa4f-9a4d-4df5-8ccc-08673dfe69b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='skipmaincontent']/div[2]/div/div/div/div[2]/div/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>bc56b680-6559-4bf9-b8f0-d4692ad2c2bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Banking
</value>
      <webElementGuid>1620ef72-77ad-4ec8-b649-303cb1df7cb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;skipmaincontent&quot;)/div[@class=&quot;container hero-container&quot;]/div[1]/div[@class=&quot;banner&quot;]/div[@class=&quot;hero-banner-module&quot;]/div[@class=&quot;banner-content-panel&quot;]/div[@class=&quot;banner-content no-offer&quot;]/h1[1]</value>
      <webElementGuid>58e25b94-0ef4-4c85-8dc2-d71639906dbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='skipmaincontent']/div[2]/div/div/div/div[2]/div/h1</value>
      <webElementGuid>982c83b0-60d3-4328-b3d2-c8b8f2229736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Popular searches'])[1]/following::h1[1]</value>
      <webElementGuid>e1d5bc62-135b-4125-a399-e398d63cc53e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search CommBank. Type search term then press Enter.'])[1]/following::h1[1]</value>
      <webElementGuid>3b71c93a-1f89-45b4-ae4d-c167a0df8a99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Everyday accounts'])[1]/preceding::h1[1]</value>
      <webElementGuid>2cff27bd-b5d6-4bc0-8de2-af8cd01a1713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Savings accounts &amp; Term Deposits'])[1]/preceding::h1[1]</value>
      <webElementGuid>80788f97-7d44-4f58-9a5c-23e5461d9cb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>b0398159-a80d-4e18-942d-0e951643928e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Banking
' or . = 'Banking
')]</value>
      <webElementGuid>0bcb3b9a-3124-4b46-b2eb-588ceb60f9bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
