<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search flights</name>
   <tag></tag>
   <elementGuidId>1f55618b-d617-481b-bbda-945a36ea0281</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.MuiButton-root.MuiButton-contained.MuiButton-containedPrimary.MuiButton-sizeLarge.MuiButton-containedSizeLarge.MuiButton-disableElevation.MuiButtonBase-root.css-1v5tbzk</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a87822e1-fc4d-4f98-965d-0b19f9a7b5cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeLarge MuiButton-containedSizeLarge MuiButton-disableElevation MuiButtonBase-root css-1v5tbzk</value>
      <webElementGuid>ac6e6ba2-19a5-45c9-96e0-ceabd3fc8f05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ccdae801-8c81-4741-9fda-e27fe8306ab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9cd54d47-b4e6-41de-91c8-4eaf834f6b52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>811ac1a2-b95a-4764-89e7-6ad7987065f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>Search flights</value>
      <webElementGuid>23ac09d9-367c-46e0-823c-cdc7caf5c5ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ds-id</name>
      <type>Main</type>
      <value>PrimaryButton</value>
      <webElementGuid>32cde192-1fbf-4c66-a9b9-d9278d3c1deb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-component-name</name>
      <type>Main</type>
      <value>search flights button</value>
      <webElementGuid>a77a7dce-d857-4cfe-9a02-2af904162fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search flights  </value>
      <webElementGuid>1c64d6ac-1412-449a-9489-2d041742610f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;MuiBox-root aurora-d37dc7&quot;]/div[@class=&quot;MuiBox-root aurora-pjornc&quot;]/div[@class=&quot;MuiContainer-root MuiContainer-maxWidthXl aurora-17wh7f7&quot;]/div[@class=&quot;MuiBox-root aurora-1ii7b30&quot;]/div[@class=&quot;MuiBox-root aurora-1a2xc0e&quot;]/div[1]/div[1]/div[@class=&quot;MuiPaper-root MuiPaper-outlined MuiPaper-rounded MuiCard-root css-1x4ecwl&quot;]/div[@class=&quot;MuiCardContent-root css-1qw96cp&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container css-15l934j&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12 MuiGrid-grid-md-5 css-1v7o2cp&quot;]/div[@class=&quot;MuiBox-root css-1etwb3r&quot;]/button[@class=&quot;MuiButton-root MuiButton-contained MuiButton-containedPrimary MuiButton-sizeLarge MuiButton-containedSizeLarge MuiButton-disableElevation MuiButtonBase-root css-1v5tbzk&quot;]</value>
      <webElementGuid>91d0011a-cf07-4081-9edd-8293f2eba129</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[7]</value>
      <webElementGuid>b5e9542b-6a28-4664-9772-b022f19e4eed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div[2]/div/div[2]/div/div/div/div/div/div/div/div[4]/div[2]/button</value>
      <webElementGuid>627d4cf2-620d-4ddb-aaf0-87c934300731</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/following::button[1]</value>
      <webElementGuid>6386be60-811c-46e5-8171-e2d8851c510d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='…'])[1]/preceding::button[1]</value>
      <webElementGuid>ae5a8e1d-a20e-482d-81f2-5e10e590910b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deals with your name on them...'])[1]/preceding::button[3]</value>
      <webElementGuid>9db0348c-8951-41b7-8628-9bfb494a54b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Search flights']/parent::*</value>
      <webElementGuid>41780e6a-ad09-4f81-8dfa-5798accb33f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/button</value>
      <webElementGuid>a49ecbca-7855-4e32-a9d3-e17d2f6b8b19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Search flights  ' or . = 'Search flights  ')]</value>
      <webElementGuid>d8a00829-d309-429c-9c45-a7abef8d77f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
