<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>4db3074c-6aef-4665-bf29-c582aa160782</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Flight Centre&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/header/div/div/div/div/div/div[3]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a8956f3b-e04a-481e-80d6-1f7168eedeeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>header-logo</value>
      <webElementGuid>da5c4adf-76b0-45fd-9727-3b2ed274452b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>200px</value>
      <webElementGuid>0c1e3f57-126f-4b9f-8296-92c3fed022ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>20px</value>
      <webElementGuid>0ff6b267-2eb3-4c13-8730-dec9510ac87c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cloudinary.fclmedia.com/fctg/image/upload/websites/fc-global/logo_white.svg</value>
      <webElementGuid>9fb738df-af8a-4cd3-85bb-0af6d7a94bbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Flight Centre</value>
      <webElementGuid>14a44255-069e-4456-ab38-e6c48d7df858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[1]/header[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-elevation4 MuiAppBar-root MuiAppBar-colorPrimary MuiAppBar-positionStatic aurora-b6dec4&quot;]/div[@class=&quot;MuiContainer-root MuiContainer-maxWidthXl aurora-dnxulr&quot;]/div[@class=&quot;MuiBox-root aurora-dpxgoq&quot;]/div[@class=&quot;aurora-j7qwjs&quot;]/div[@class=&quot;aurora-ztssqm&quot;]/div[@class=&quot;aurora-1xhj18k&quot;]/div[@class=&quot;MuiBox-root aurora-1ia6xgx&quot;]/a[@class=&quot;MuiTypography-root MuiTypography-inherit MuiLink-root MuiLink-underlineAlways aurora-1dvjwkn&quot;]/img[1]</value>
      <webElementGuid>16901e7c-6f19-4f0c-be09-540a7e4d1290</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/header/div/div/div/div/div/div[3]/a/img</value>
      <webElementGuid>118d6ff3-3f3f-45d5-b627-5ea6e4b88d06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Flight Centre']</value>
      <webElementGuid>4a4b9138-b7fa-4851-8c3f-5a9216c06e6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>1e0d240b-b3f5-4845-871a-4b2436e113ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cloudinary.fclmedia.com/fctg/image/upload/websites/fc-global/logo_white.svg' and @alt = 'Flight Centre']</value>
      <webElementGuid>6e9c20ea-cb7c-4445-a6cf-668520ec836b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
