<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Sitemap_ImagePopupBlockReadOnly__Intern_cee081</name>
   <tag></tag>
   <elementGuidId>9861ecb5-2b51-4fce-8aeb-576b1c5c8bee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.ImagePopupBlockReadOnly__InternalImage-sc-1boptuc-5.bFjOzu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wisepops-wisepop-scrollable-324582']/div/div/div/div[2]/div/div/a/span/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4f5919d2-99e3-4e39-9828-ff7a0fbbd5fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//cdn.wisepops.com/shared/images/wisepops/c.59622/e0bdf398888401a8ca7a01a951b12deb.jpg</value>
      <webElementGuid>804fa8e5-1ba3-4ece-97b5-d331124df3a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>DD-8786_AU_NZ_600x400</value>
      <webElementGuid>d3a2e144-f471-4f92-9bc5-325209360739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ImagePopupBlockReadOnly__InternalImage-sc-1boptuc-5 bFjOzu</value>
      <webElementGuid>a74b3c47-27c4-4086-869f-51435a586655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wisepops-wisepop-scrollable-324582&quot;)/div[@class=&quot;Popup__WisepopContent-sc-1vpebv6-2 kzITAm wisepops-content&quot;]/div[@class=&quot;VideoStopper__Container-jc37qi-0 brUTwo&quot;]/div[@class=&quot;BlocksContainer-sc-3tl3gf-0 fYeppA wisepops-column&quot;]/div[@class=&quot;wisepops-blocks-wrapper&quot;]/div[@class=&quot;BlockReadOnly__BlockContainerReadOnly-sc-1sk33k3-0 SdpMH&quot;]/div[@class=&quot;ImagePopupBlockReadOnly__Container-sc-1boptuc-0 ilSiwk wisepops-block-image wisepops-block-id-1692961&quot;]/a[@class=&quot;ImagePopupBlockReadOnly__ImageLink-sc-1boptuc-2 hKcWWD&quot;]/span[@class=&quot;ImagePopupBlockReadOnly__ImagePlacer-sc-1boptuc-4 brlPnP&quot;]/img[@class=&quot;ImagePopupBlockReadOnly__InternalImage-sc-1boptuc-5 bFjOzu&quot;]</value>
      <webElementGuid>fdc6048b-da61-46fe-a50d-eb7c77b016b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wisepops-wisepop-scrollable-324582']/div/div/div/div[2]/div/div/a/span/img</value>
      <webElementGuid>fdfa4518-45c3-49a8-ab28-d92e672531d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='DD-8786_AU_NZ_600x400']</value>
      <webElementGuid>b591b45e-aeb7-485c-a1aa-abbe5cbde189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/img</value>
      <webElementGuid>5b28b4ce-8f5d-4c74-9dd4-4a6f4a80bfa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//cdn.wisepops.com/shared/images/wisepops/c.59622/e0bdf398888401a8ca7a01a951b12deb.jpg' and @alt = 'DD-8786_AU_NZ_600x400']</value>
      <webElementGuid>5804ffb6-6dda-4a50-8cc8-58a41b1c9434</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
