<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Sitemap_ImagePopupBlockReadOnly__Intern_cee081</name>
   <tag></tag>
   <elementGuidId>9861ecb5-2b51-4fce-8aeb-576b1c5c8bee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wisepops-wisepop-scrollable-324582']/div/div/div/div[2]/div/div/a/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.ImagePopupBlockReadOnly__InternalImage-sc-1boptuc-5.bFjOzu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f61364b3-1bb3-4c50-aea3-40d0079f0573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//cdn.wisepops.com/shared/images/wisepops/c.59622/e0bdf398888401a8ca7a01a951b12deb.jpg</value>
      <webElementGuid>35fe1719-6291-4527-953d-b013e1859d77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>DD-8786_AU_NZ_600x400</value>
      <webElementGuid>f1c2e0d7-972e-444e-b9d4-7016a60a6b19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ImagePopupBlockReadOnly__InternalImage-sc-1boptuc-5 bFjOzu</value>
      <webElementGuid>30d5a710-3d56-4a54-90f3-385822864d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wisepops-wisepop-scrollable-324582&quot;)/div[@class=&quot;Popup__WisepopContent-sc-1vpebv6-2 kzITAm wisepops-content&quot;]/div[@class=&quot;VideoStopper__Container-jc37qi-0 brUTwo&quot;]/div[@class=&quot;BlocksContainer-sc-3tl3gf-0 fYeppA wisepops-column&quot;]/div[@class=&quot;wisepops-blocks-wrapper&quot;]/div[@class=&quot;BlockReadOnly__BlockContainerReadOnly-sc-1sk33k3-0 SdpMH&quot;]/div[@class=&quot;ImagePopupBlockReadOnly__Container-sc-1boptuc-0 ilSiwk wisepops-block-image wisepops-block-id-1692961&quot;]/a[@class=&quot;ImagePopupBlockReadOnly__ImageLink-sc-1boptuc-2 hKcWWD&quot;]/span[@class=&quot;ImagePopupBlockReadOnly__ImagePlacer-sc-1boptuc-4 brlPnP&quot;]/img[@class=&quot;ImagePopupBlockReadOnly__InternalImage-sc-1boptuc-5 bFjOzu&quot;]</value>
      <webElementGuid>8b771c18-d943-45e3-b9aa-cabdeeed64e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wisepops-wisepop-scrollable-324582']/div/div/div/div[2]/div/div/a/span/img</value>
      <webElementGuid>71ffeb03-b051-455b-9748-69d5450c8af7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='DD-8786_AU_NZ_600x400']</value>
      <webElementGuid>7fccc53e-640e-42f4-9737-5839d53bc6aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/img</value>
      <webElementGuid>f6010ecb-c1de-4693-81ee-3f785db2904c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//cdn.wisepops.com/shared/images/wisepops/c.59622/e0bdf398888401a8ca7a01a951b12deb.jpg' and @alt = 'DD-8786_AU_NZ_600x400']</value>
      <webElementGuid>596cccde-3f16-42df-88ea-18242431341b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
