<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Book appointment</name>
   <tag></tag>
   <elementGuidId>21b62c4d-a7dc-44e5-894f-297007512a91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CB-HL-HERO']/div/div/div[2]/div/div[2]/p/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.button_primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>de462d80-2acb-45ee-938e-9c51f47d1f06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Book appointment</value>
      <webElementGuid>948eb351-fecc-4fbc-a59a-2c09a0372950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.commbank.com.au/digital/homeloanappointment?ei=cta-hlhero-appt</value>
      <webElementGuid>34565343-e717-4168-8747-cdfdb2e02ae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button_primary</value>
      <webElementGuid>127f4048-77fb-4296-98d3-f44c2d0de12c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracker-type</name>
      <type>Main</type>
      <value>hlc</value>
      <webElementGuid>c274ae5e-ded1-439c-9381-a5687e63cfd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracker_ei</name>
      <type>Main</type>
      <value>default_0_2</value>
      <webElementGuid>7969eb02-b7c9-4dc9-ad5a-c84d4ca0a25f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracker-id</name>
      <type>Main</type>
      <value>default_0_2</value>
      <webElementGuid>f5747086-cdb6-4f11-9981-5e18c1e83c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>d95a9b74-3cdc-46f6-a90f-07af4d75337c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Book appointment</value>
      <webElementGuid>89dd8329-3246-4f43-96a8-6bb0c737a117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CB-HL-HERO&quot;)/div[@class=&quot;default banner&quot;]/div[@class=&quot;hero-banner-module&quot;]/div[@class=&quot;banner-content-panel&quot;]/div[@class=&quot;banner-content no-offer&quot;]/div[@class=&quot;cta&quot;]/p[1]/a[@class=&quot;button_primary&quot;]</value>
      <webElementGuid>1552cd36-8182-42d9-a474-d450eb91e741</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CB-HL-HERO']/div/div/div[2]/div/div[2]/p/a[2]</value>
      <webElementGuid>72af77dc-1e02-4dea-b594-ee5ef97c390f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Book appointment')]</value>
      <webElementGuid>f1b17fc0-3cb7-49ec-a8d0-70ff86fc83fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='See our competitive variable rate'])[1]/following::a[1]</value>
      <webElementGuid>6142d8fd-e05d-4be4-9894-bcc53a8a4f4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home loans'])[3]/following::a[2]</value>
      <webElementGuid>9ad08530-fb7a-4882-a0cf-219a2d059adc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buying a new home'])[1]/preceding::a[1]</value>
      <webElementGuid>da1937b8-283b-4e4f-b6c5-877b849d8aeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refinance your home loan'])[1]/preceding::a[2]</value>
      <webElementGuid>1ba18d00-c31b-48ed-bd32-0cbc05e090af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Book appointment']/parent::*</value>
      <webElementGuid>e0edccf2-85f0-47a6-b400-9b640cdfa689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.commbank.com.au/digital/homeloanappointment?ei=cta-hlhero-appt')]</value>
      <webElementGuid>7d901be7-f848-4e33-a601-cd5aa5510ec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a[2]</value>
      <webElementGuid>8ea10520-c7c5-4a7f-9e6a-1f7f3a8a6a88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.commbank.com.au/digital/homeloanappointment?ei=cta-hlhero-appt' and (text() = 'Book appointment' or . = 'Book appointment')]</value>
      <webElementGuid>fcc5c0ec-3e6c-4fcd-ac0c-a809e16c41a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
