<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_See our competitive variable rate</name>
   <tag></tag>
   <elementGuidId>56dc0916-88ef-48fc-956d-474a856a997b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CB-HL-HERO']/div/div/div[2]/div/div[2]/p/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.button_secondary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>16515145-5ce8-40e3-b0ba-4f3708daa57c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>See our competitive variable rate</value>
      <webElementGuid>d8b00569-1da8-43f4-ad2c-85df9f49f57f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/home-loans/standard-variable-rate.html?ei=cta-svr</value>
      <webElementGuid>a77d6aec-631e-4201-95e7-69fe5a433738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button_secondary</value>
      <webElementGuid>7c538b9c-321f-4d40-955a-ce296484a164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracker-type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1883b36f-3bd6-4c6c-8628-89a0c16f7669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracker_ei</name>
      <type>Main</type>
      <value>default_0_1</value>
      <webElementGuid>8c1771bc-2bf1-405a-ac0a-0e2f67e1f171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracker-id</name>
      <type>Main</type>
      <value>default_0_1</value>
      <webElementGuid>3f372be5-0081-487e-ad5d-ef3004ad544b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>See our competitive variable rate</value>
      <webElementGuid>b9430a87-3f16-4811-a3bf-8983b1667f2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CB-HL-HERO&quot;)/div[@class=&quot;default banner&quot;]/div[@class=&quot;hero-banner-module&quot;]/div[@class=&quot;banner-content-panel&quot;]/div[@class=&quot;banner-content no-offer&quot;]/div[@class=&quot;cta&quot;]/p[1]/a[@class=&quot;button_secondary&quot;]</value>
      <webElementGuid>7a659c94-564c-4594-a9e1-88a0a8924b4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CB-HL-HERO']/div/div/div[2]/div/div[2]/p/a</value>
      <webElementGuid>a9ee83d6-4ea5-436d-941c-30a6a4d03973</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'See our competitive variable rate')]</value>
      <webElementGuid>15d7d25e-a052-4700-8abe-b9ee23c888a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home loans'])[3]/following::a[1]</value>
      <webElementGuid>4cdb7198-2e60-4ee9-ac6d-80c081b02350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Popular searches'])[1]/following::a[10]</value>
      <webElementGuid>d614813c-c900-43e2-92d7-43efb7cd4667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book appointment'])[1]/preceding::a[1]</value>
      <webElementGuid>40246f72-b3c3-4720-9f14-dad5915143ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buying a new home'])[1]/preceding::a[2]</value>
      <webElementGuid>183f9917-c1a1-4a7b-8c8f-016ab91832e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='See our competitive variable rate']/parent::*</value>
      <webElementGuid>54cafb62-351e-4749-bd9c-3f71813f523b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/home-loans/standard-variable-rate.html?ei=cta-svr')]</value>
      <webElementGuid>16df6719-5c00-483b-b0a1-3d7d2beb5c7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
      <webElementGuid>bb43147e-380b-4883-9b5b-f1ba527aad7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/home-loans/standard-variable-rate.html?ei=cta-svr' and (text() = 'See our competitive variable rate' or . = 'See our competitive variable rate')]</value>
      <webElementGuid>d1d43a82-c66b-42fe-99cd-13c44aa92a5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
