<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Skip to main content_LPMcloseButton-168_663385</name>
   <tag></tag>
   <elementGuidId>b1cb1b63-85ea-41ad-80dc-d43b5b9f0315</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='LPMcloseButton-1689582551687-3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#LPMcloseButton-1689582551687-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>373a7f95-d815-4ae4-986e-4dfe0a69527e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://static.my.commbank.com.au/static/cmxAssets/Webchat/invites/LinkNotNow-padding.png</value>
      <webElementGuid>601ead69-5619-4dda-9045-edce8d07ca05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LPMcloseButton-1689582551687-3</value>
      <webElementGuid>ee9c5d8e-6200-4303-a84c-428011eccd7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Chat Invitation - Decline</value>
      <webElementGuid>dafaccdf-0dce-49e9-93ae-79b53d92a854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>LPMcloseButton</value>
      <webElementGuid>a1e36d4e-cc63-43a1-901b-f6c2d4cce43c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lp-event</name>
      <type>Main</type>
      <value>close</value>
      <webElementGuid>dbb6681c-36f9-4867-bce9-55c4386bf2a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>72a295d1-dbdb-42b0-a259-82bfe3c0dcef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c3f94f51-c874-43bf-9d90-f68389b1f5fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Chat Invitation - Decline</value>
      <webElementGuid>8ae8adf2-1c64-4be7-916a-a2051ed90a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LPMcloseButton-1689582551687-3&quot;)</value>
      <webElementGuid>076a4ce7-f59c-4057-a2d0-69de20a4a327</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='LPMcloseButton-1689582551687-3']</value>
      <webElementGuid>67eef53f-ab88-412d-95ac-654b0f248eeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LPMcontainer-1689582551686-0']/img</value>
      <webElementGuid>8b18acb9-9c8f-47a0-9cc8-d9a5b0713493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Chat Invitation - Decline']</value>
      <webElementGuid>080b833a-6e75-4bfc-a3e9-953bb17d31b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/div/img</value>
      <webElementGuid>c7d81059-ee0b-4d06-ba01-dce2afcf7f99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://static.my.commbank.com.au/static/cmxAssets/Webchat/invites/LinkNotNow-padding.png' and @id = 'LPMcloseButton-1689582551687-3' and @alt = 'Chat Invitation - Decline']</value>
      <webElementGuid>6a8f6121-cd58-4300-b93a-f707bc5175f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
