<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next_1_2_3</name>
   <tag></tag>
   <elementGuidId>7f35f463-391e-4763-b40f-3e02bbdfcbae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='dob-btn-continue']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dob-btn-continue</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>65235de6-0363-40c4-9863-6e90979139bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dob-btn-continue</value>
      <webElementGuid>84c9b6fe-21bb-49ad-b0d7-b9cd468fd994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-action</value>
      <webElementGuid>946774aa-0476-4965-9230-878d4800cfe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b320e004-c224-4292-80fb-07b30c721c98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>ca71bd97-1d83-4bcd-bf57-15378955677b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dob-btn-continue&quot;)</value>
      <webElementGuid>aaa0cede-c28b-49c1-823c-877c2267b698</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='dob-btn-continue']</value>
      <webElementGuid>7a5bc85f-4dbc-4691-b26e-5982aba87c04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='date-of-birth-blade']/div[3]/div[3]/button</value>
      <webElementGuid>b482ce98-41c2-474a-9135-f6a772ebb239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You entered'])[1]/following::button[1]</value>
      <webElementGuid>dc1f56fd-c92d-404c-bbd5-46f0e7c21d2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Make sure your date of birth is correct - it can only be changed at a branch:'])[1]/following::button[1]</value>
      <webElementGuid>dcd11722-4745-4033-8fa9-acab2aeb0ff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'dob-btn-continue', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>f78ad47b-5449-4b21-bdb1-b5c71ae9df7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/button</value>
      <webElementGuid>98cf91dd-7dff-45e7-a3ac-2d9d7918321d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'dob-btn-continue' and @type = 'button' and (text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>9f97d451-bbf4-412f-a1a7-c5e29e189bc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
