<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Get started</name>
   <tag></tag>
   <elementGuidId>6321f325-16b2-460a-b9b9-be74a399ea90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='get-started-btn-ok']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#get-started-btn-ok</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7cebd8d7-0706-4da0-bf8a-42e1cc8d47be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>get-started-btn-ok</value>
      <webElementGuid>d33abb0b-4ff5-4dac-8dfd-8993f9ad2cbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-action--emphasis</value>
      <webElementGuid>c75de63a-bc1a-4b64-bb1a-afd797cee5a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>daa1016b-501c-448c-9416-5f5f5652e797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Get started</value>
      <webElementGuid>c32ab9dc-2800-462b-b059-8eeb577231ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;get-started-btn-ok&quot;)</value>
      <webElementGuid>fc4230e8-e065-45d9-88dd-ee74b8ec0b1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='get-started-btn-ok']</value>
      <webElementGuid>93448917-0ad7-4cbb-b59e-4d81b3e38ae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='get-started-blade']/div[2]/button</value>
      <webElementGuid>c42abf5f-5666-43c7-bb36-b6a0259ec005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created with Sketch.'])[4]/following::button[1]</value>
      <webElementGuid>a4f305e5-79cc-403f-9a74-0cbdfdcecc75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visit our Youth page'])[1]/following::button[1]</value>
      <webElementGuid>02eed53f-7b0c-401e-8eb9-f1a56f721da9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'get-started-btn-ok', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>1e2debca-184d-4ab0-acaf-85a0710dea97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Get started']/parent::*</value>
      <webElementGuid>d4cbf879-5da0-475e-afef-6aac894045ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[2]/button</value>
      <webElementGuid>041ea0fe-457a-4dab-9a8d-7b20540f6636</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'get-started-btn-ok' and @type = 'button' and (text() = 'Get started' or . = 'Get started')]</value>
      <webElementGuid>6ef4a6ba-e298-4372-9b06-aa2783821bbb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
