<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Open Smart Access only</name>
   <tag></tag>
   <elementGuidId>d3631991-e12a-4de6-ae8f-9cc89a9bef20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='savings-account-btn-no']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#savings-account-btn-no</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>93ea2bd3-2210-4286-b5d4-1285a5e17605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>savings-account-btn-no</value>
      <webElementGuid>9048547c-cab9-4666-ac66-7578a17aba97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-action</value>
      <webElementGuid>fcd3bb7d-088a-43ff-8e66-28d0572c7fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1c6bb30a-849e-4601-888c-4b9b66bc4f3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Open Smart Access only</value>
      <webElementGuid>69fa19de-af80-474a-9b76-cd7dca9e3aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;savings-account-btn-no&quot;)</value>
      <webElementGuid>20d0b97f-a30d-4107-be29-7ef8e83308f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='savings-account-btn-no']</value>
      <webElementGuid>0cf2f348-4566-4017-920f-0950ece2e09c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='savings-account-blade']/div[3]/button[2]</value>
      <webElementGuid>e9b34068-888f-40b7-b2fe-fdc5cb2b7665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add a NetBank Saver'])[1]/following::button[1]</value>
      <webElementGuid>a34445c5-80c8-4909-b86b-2086381e1f9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created with Sketch.'])[9]/following::button[2]</value>
      <webElementGuid>b4026958-4c2d-4a36-a5cf-c041138ead99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'savings-account-btn-no', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>9fc59bfb-fea0-448a-8a91-634d90b3cb97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Open Smart Access only']/parent::*</value>
      <webElementGuid>5e6bcaa1-a456-41f4-a085-f0cea4ebfa49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[3]/button[2]</value>
      <webElementGuid>85d4567d-b78f-43d6-bd56-bc61758ac625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'savings-account-btn-no' and @type = 'button' and (text() = 'Open Smart Access only' or . = 'Open Smart Access only')]</value>
      <webElementGuid>f5a379fa-fa12-433d-ac93-aca1c0f987e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
