<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next_1</name>
   <tag></tag>
   <elementGuidId>f19f9b38-4214-4c88-9e0d-aafb0af43bdd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='name-btn-continue']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#name-btn-continue</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8a7eadfb-6131-4d3c-99e6-051b989702bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>name-btn-continue</value>
      <webElementGuid>7e0a16a1-37b9-4842-9e80-74f0a67fa50a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-action</value>
      <webElementGuid>c8c47a1f-16ca-4b6f-9c6f-63dfb7b7a7e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>03d56da5-6952-498f-97da-01696b3d3ee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>55ea026c-319a-46bb-a766-e9660f227d53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;name-btn-continue&quot;)</value>
      <webElementGuid>68a053c6-02b3-4db3-b4cf-c1d6f3e0cbdc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='name-btn-continue']</value>
      <webElementGuid>bfbfc08b-917e-4090-a852-7137fe0e8a91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='name-blade']/div[3]/button</value>
      <webElementGuid>909c982a-da87-4d6b-af31-f2ba88a13f1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last name'])[1]/following::button[1]</value>
      <webElementGuid>6e18ad18-8509-44fa-bd33-024b469eebe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Middle name(s) - if you have one'])[1]/following::button[1]</value>
      <webElementGuid>9413337c-eefb-4d38-833f-4f46bf7bbf86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'name-btn-continue', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>6765b1ec-b93e-400e-91e3-3499807890ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div[3]/button</value>
      <webElementGuid>ebe62872-5f70-40ac-b95a-1a41bbf5078c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'name-btn-continue' and @type = 'button' and (text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>426a716c-64ee-4e7a-8ab6-c58ec4d60e5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
