<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Switch from variable rate to fixed rate</name>
   <tag></tag>
   <elementGuidId>90c3c1ef-5716-4724-a216-c1b104e8def5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='button-SelfServe-VariableToFixed']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#button-SelfServe-VariableToFixed</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>16828d1e-e2fd-4a7d-8d87-834bd975f273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-link</value>
      <webElementGuid>8a1ffcf9-0969-4938-a4d1-d0d9f0198e11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-SelfServe-VariableToFixed</value>
      <webElementGuid>bb1fb88a-34d6-4ecc-9f48-cab11f3c388c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/digital/homeloanswitching?ei=cal3-variabletofixed</value>
      <webElementGuid>3e3c14dd-f74b-46e5-9391-6d1f90bd1827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>next</value>
      <webElementGuid>5c4e0dc9-c478-46b8-ad32-44e04aa7e265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Switch from variable rate to fixed rate</value>
      <webElementGuid>51274ecf-5eff-47e4-bd9a-9f16dfc7245f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-SelfServe-VariableToFixed&quot;)</value>
      <webElementGuid>a54deb56-57fd-4bf5-b046-a56e32f13afd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='button-SelfServe-VariableToFixed']</value>
      <webElementGuid>69127ce5-d38a-4e8d-8941-d4ee94d5587e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='homeLoanAppointmentIntroV2']/div/div[2]/div[3]/div[2]/a</value>
      <webElementGuid>0d4eec39-991e-446b-958c-790435871013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Switch from variable rate to fixed rate')]</value>
      <webElementGuid>66a12a0a-f82e-43ef-93fa-f9c8d1fbfaab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change your loan'])[2]/following::a[1]</value>
      <webElementGuid>010de8a4-8b47-47f0-98d3-caceb95dd839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change your existing loan online'])[1]/following::a[1]</value>
      <webElementGuid>409dadaa-4c5b-4612-acff-20ea032cb387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refix your loan (if your fixed rate is expiring soon)'])[1]/preceding::a[1]</value>
      <webElementGuid>5c01edff-7f20-49c4-a263-1b45a4c00f7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Split your loan'])[1]/preceding::a[2]</value>
      <webElementGuid>04b6995f-459d-4d6e-a47e-909a2f1eda2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Switch from variable rate to fixed rate']/parent::*</value>
      <webElementGuid>c375e72c-867b-4b63-ab67-48c268fa9da8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/digital/homeloanswitching?ei=cal3-variabletofixed')]</value>
      <webElementGuid>6249b49a-ca97-4ecc-8258-fb9a58da0345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>e00a39f5-f602-4dbe-b118-0cc4fb9869b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'button-SelfServe-VariableToFixed' and @href = '/digital/homeloanswitching?ei=cal3-variabletofixed' and (text() = 'Switch from variable rate to fixed rate' or . = 'Switch from variable rate to fixed rate')]</value>
      <webElementGuid>f303acca-7a7c-415c-98fe-8404b9971679</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
