<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>79e6752b-c18a-4951-995e-c371af913f5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Bunnings&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-header']/div/div/div[2]/h1/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5ae56e01-68ee-4187-8a3e-e060b018d579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Bunnings</value>
      <webElementGuid>27414dcc-1f9a-4ae6-8c5c-ae49371519ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stylelabs-content-id</name>
      <type>Main</type>
      <value>3832610</value>
      <webElementGuid>cff8079c-4a94-4554-8900-028b51cc49c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>thumbnailsrc</name>
      <type>Main</type>
      <value>https://bunningscontenthub.bunnings.com.au/api/gateway/3832610/thumbnail</value>
      <webElementGuid>f9a97ebb-b0be-4245-83f2-5b985cd7e953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stylelabs-content-type</name>
      <type>Main</type>
      <value>Image</value>
      <webElementGuid>129c1aee-61f5-4d7e-8707-15b21dbac333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>c5627beb-2050-479e-8893-d4d261becbee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>139</value>
      <webElementGuid>b2498176-311d-48ad-b7d3-f125dde180c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media.prod.bunnings.com.au/api/public/content/f8fd8d792b5844169c246d4de0ed11cf?v=cb26e455</value>
      <webElementGuid>55431773-b8bc-4d1a-960e-141770df2c0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-header&quot;)/div[@class=&quot;MuiGrid-root header-grid MuiGrid-container MuiGrid-align-items-xs-center&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-9&quot;]/div[@class=&quot;sc-9b668e38-8 bwwAGT&quot;]/h1[@class=&quot;MuiTypography-root pageLogoTitle MuiTypography-h1&quot;]/a[@class=&quot;sc-f5bef339-1 gPIdEa&quot;]/img[1]</value>
      <webElementGuid>2fd273bc-446f-4fa6-abeb-42394c7754b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-header']/div/div/div[2]/h1/a/img</value>
      <webElementGuid>4e91b1da-b52b-4b8c-935e-101a97dc3fc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Bunnings']</value>
      <webElementGuid>0d59367f-d0ab-4dcf-ba48-44974b381a15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>779c0fcb-8bf7-48b2-acf6-a4fa92779dc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Bunnings' and @src = 'https://media.prod.bunnings.com.au/api/public/content/f8fd8d792b5844169c246d4de0ed11cf?v=cb26e455']</value>
      <webElementGuid>cb8823d4-23c1-4131-9afb-521c3d2b9427</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
