<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Hire Shop_q</name>
   <tag></tag>
   <elementGuidId>1e2f421e-4a59-4f11-aebd-8a485112afa5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#custom-css-outlined-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='custom-css-outlined-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>41aa1b25-ea92-4511-af66-f675c2487677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>c0ce5c66-ab2a-4d76-bbf5-13d7cad57b08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>32528329-e67f-4de3-a4f6-89cda8d7ee8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>custom-css-outlined-input-helper-text</value>
      <webElementGuid>84a5e5bb-9c3e-4663-b207-0d6b637a818d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a1a6dcdb-bd0f-43cf-ab2a-55ba773d5ed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>custom-css-outlined-input</value>
      <webElementGuid>45b4ac4e-24e8-4ebb-8478-b0356375258e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>q</value>
      <webElementGuid>b4ae61c5-454e-45dc-9947-2cea4895c66b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search products and more</value>
      <webElementGuid>2c6126e7-f081-46ee-adec-6c10ea612d14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>949d507a-6eae-4c20-8da3-8510cb1969d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputTypeSearch MuiInputBase-inputMarginDense MuiOutlinedInput-inputMarginDense</value>
      <webElementGuid>60aa2d6d-4cca-4f7a-ba15-5e3f3f3e79b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-di-id</name>
      <type>Main</type>
      <value>#custom-css-outlined-input</value>
      <webElementGuid>b5a37984-ab02-4263-b458-8f39c9f89dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;custom-css-outlined-input&quot;)</value>
      <webElementGuid>80e38ece-2cde-4671-8a3a-fde35a9b1a09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='custom-css-outlined-input']</value>
      <webElementGuid>bae92092-30e8-4c77-89c1-0b477fd88fa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='header-search']/label/div/div/input</value>
      <webElementGuid>5b3cfd71-65a7-4c6d-9832-c7c2b5c0886c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>587ee336-15f9-4c64-974b-3bd5b3fc7843</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'custom-css-outlined-input' and @name = 'q' and @placeholder = 'Search products and more']</value>
      <webElementGuid>38aeabce-9380-4178-8699-10fc094c6cdd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
