<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Atlanta, GA</name>
   <tag></tag>
   <elementGuidId>2ca2bf05-fac9-48d8-beec-b5fb6f6bc198</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bigsearch-query-location-suggestion-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bigsearch-query-location-suggestion-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3bf01dfc-98a8-4770-9a71-31820bd95220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>s1wh3te4 atm_9j_tlke0l atm_9s_1txwivl atm_cx_exct8b atm_lb_logulu atm_lj_18j4z7t atm_li_iqwws s1esy3c5 atm_2d_1nh1gcj dir dir-ltr</value>
      <webElementGuid>856a0492-2c39-4f0e-a4a2-23d25af77619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>68f28baa-cb61-4ab9-aa23-1dda957018d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>4f340830-4b52-4af0-8b98-a971a9ea1506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bigsearch-query-location-suggestion-0</value>
      <webElementGuid>0481b5a4-9ad7-4a2e-9d88-a2123cf2d0d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ad32dbb1-4b27-40b9-a05f-4c547949ada8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>option-0</value>
      <webElementGuid>2b1219e2-6b8f-448b-b03b-5f2a49105c48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Atlanta, GA</value>
      <webElementGuid>cf35af9f-741b-4aa2-a242-72f3df6cdec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bigsearch-query-location-suggestion-0&quot;)</value>
      <webElementGuid>4f371eed-cc7e-4514-b284-ba103b41bf8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='bigsearch-query-location-suggestion-0']</value>
      <webElementGuid>628b4f2a-695b-412a-82c0-f089931aff7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bigsearch-query-location-listbox']/div</value>
      <webElementGuid>30a502a2-5cdf-437b-a01f-fbc9b4e5093c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Where'])[1]/following::div[6]</value>
      <webElementGuid>51546731-e0b0-4681-ad6c-0de79d0e4fd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Online Experiences'])[1]/following::div[12]</value>
      <webElementGuid>1b533fd2-7afb-4ff8-b0bd-8bbd397a99f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atlanta, Downtown, GA'])[1]/preceding::div[5]</value>
      <webElementGuid>8d383186-24de-4321-a560-9823df8fc328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div</value>
      <webElementGuid>b21f7578-bd32-4845-8ae5-fa57a8dd6d83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'bigsearch-query-location-suggestion-0' and (text() = 'Atlanta, GA' or . = 'Atlanta, GA')]</value>
      <webElementGuid>edab95e7-a3e1-40c9-b5fd-ee0c30ef41bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
