<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Where_query</name>
   <tag></tag>
   <elementGuidId>efde6195-abe6-4175-8c44-57e6c2b65020</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bigsearch-query-location-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bigsearch-query-location-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c07643ac-bfce-4fed-affc-06e1bcd46de8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iluujbk dir dir-ltr focus-visible</value>
      <webElementGuid>87ce23cf-70f7-48a4-9df9-f660f1e1d8da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>2d1f84fe-6bfe-4f9e-ae19-16240f2dd06c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8b2cea00-aa40-4e2d-8276-fe46184dcc93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>11317858-10a5-42d4-8d6e-07179d36229b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>014e22f8-dc2e-4759-91f6-86ff5474c18a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bigsearch-query-location-input</value>
      <webElementGuid>98d2435e-3ca1-40ca-b681-78e3997cd2a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>query</value>
      <webElementGuid>912dc1e5-ea00-4346-9669-60ebf4031db5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>bigsearch-query-location-description</value>
      <webElementGuid>62e8a5a7-e7ed-4bc6-b5b2-0ce1ff36a2a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search destinations</value>
      <webElementGuid>75e1aae7-2903-43c5-a30c-71132c6d162d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>structured-search-input-field-query</value>
      <webElementGuid>e0674eef-5aa1-4902-bd58-7265b84940a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bigsearch-query-location-input&quot;)</value>
      <webElementGuid>06b51e1e-1763-47b6-a771-f5cac301d90c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bigsearch-query-location-input']</value>
      <webElementGuid>35fcb2d7-f942-47f9-acf0-5f364bb60e2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search-tabpanel']/div/div/div/label/div/input</value>
      <webElementGuid>761ff9ec-9a6d-4e59-a444-0421a4095026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div/input</value>
      <webElementGuid>2f9f1b1e-ad86-4dc9-8c79-850b8b0f04d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'bigsearch-query-location-input' and @name = 'query' and @placeholder = 'Search destinations']</value>
      <webElementGuid>87aa7689-95f8-4864-b9b1-d09dd812086c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
