<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>319342bf-c761-4cd3-b1f3-5faf9e5f94d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='body']/div[12]/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[title=&quot;Usabilla Feedback Form&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>0e505d75-1b6c-487f-bd79-462b882bef21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ed9b7dfb-4e15-4606-9de8-8335f4ffbb8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3b77657e-adc6-4f2f-9088-c454c92bc56e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>32b4cd3b-e86a-4113-af56-080834e1e795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Usabilla Feedback Form</value>
      <webElementGuid>1922dc52-4918-461b-ae6c-9f5a482e85e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d6tizftlrpuof.cloudfront.net/live/i/54255e1c1ac90d5c6687028d/42399cc4d9df31ae90765579277049085bbc7040.html?tags=right</value>
      <webElementGuid>29c60c6c-4f8d-425e-a92e-b19dd3cd9680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8bc8b587-aab9-4b27-a0fa-7bb79b606071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body&quot;)/div[@class=&quot;usabilla__overlay&quot;]/iframe[1]</value>
      <webElementGuid>3ca2597f-ea4c-4180-ae39-2b6eb59da16e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='body']/div[12]/iframe</value>
      <webElementGuid>7f391ee2-eab5-4418-aca4-575b657701ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/iframe</value>
      <webElementGuid>cb1d71b2-9de5-4b40-96cf-809b4b00c37b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'Usabilla Feedback Form' and @src = 'https://d6tizftlrpuof.cloudfront.net/live/i/54255e1c1ac90d5c6687028d/42399cc4d9df31ae90765579277049085bbc7040.html?tags=right']</value>
      <webElementGuid>9e5f897e-b91a-4f41-8b48-4303e35b8538</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
