<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Bank  savings accounts</name>
   <tag></tag>
   <elementGuidId>6b0cd74b-594b-46de-9156-10c0bb587a6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='skipmaincontent']/div[2]/div/div/div/div/div/div[3]/div/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.hyperlink-list > li > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>626769f1-8a26-49c4-aeb1-45bf796a86f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/bank-accounts.html?ei=hp-prodnav_BA</value>
      <webElementGuid>55e7b7f6-1342-4804-8357-2e15f1f32832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracker-type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7938e1f5-3f56-475b-9242-395c842235d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracker_ei</name>
      <type>Main</type>
      <value>default_0_1</value>
      <webElementGuid>13ec090b-923f-4950-8fa0-435f8dc722c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracker-id</name>
      <type>Main</type>
      <value>default_0_1</value>
      <webElementGuid>b387d2a3-fd11-4e72-8f71-b662c1039012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bank &amp; savings accounts</value>
      <webElementGuid>403ef675-b5fc-487d-bd9c-c66641ff5b55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;skipmaincontent&quot;)/div[@class=&quot;container content-container&quot;]/div[@class=&quot;homepage-six-pack&quot;]/div[@class=&quot;six-packs-module bottom-divider standard-spacing&quot;]/div[@class=&quot;six-packs-wrapper&quot;]/div[@class=&quot;six-pack-links&quot;]/div[1]/div[@class=&quot;items-list mobile-accordion-body&quot;]/div[1]/ul[@class=&quot;hyperlink-list&quot;]/li[1]/a[1]</value>
      <webElementGuid>c648348b-0358-4821-895a-3bf3667489dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='skipmaincontent']/div[2]/div/div/div/div/div/div[3]/div/ul/li/a</value>
      <webElementGuid>0943ae53-e313-4c31-83c8-c3f1b5a28c0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Bank &amp; savings accounts')]</value>
      <webElementGuid>bfcd38b2-5551-4674-98a0-6da59ec9e2c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Banking'])[4]/following::a[1]</value>
      <webElementGuid>c8bcfbb7-e82a-4bf7-8119-2e331910a95b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Banking'])[3]/following::a[1]</value>
      <webElementGuid>b6600b08-7d2b-42b9-a8fb-6c90140c19ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit cards'])[1]/preceding::a[1]</value>
      <webElementGuid>a074e0dc-3b9f-45a8-91c3-a72ab6a1f2cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal loans'])[1]/preceding::a[2]</value>
      <webElementGuid>568f35ca-83c4-45dd-bcdd-3e2db24fc9cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/bank-accounts.html?ei=hp-prodnav_BA')]</value>
      <webElementGuid>b57ea531-29f3-4c48-bb3d-7fd7084ec43c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/ul/li/a</value>
      <webElementGuid>583481e0-a474-496e-8b07-1e21ba58939a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/bank-accounts.html?ei=hp-prodnav_BA' and (text() = 'Bank &amp; savings accounts' or . = 'Bank &amp; savings accounts')]</value>
      <webElementGuid>3fceeb58-581c-422f-ae16-d3963b9061ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
