<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_See all everyday accounts</name>
   <tag></tag>
   <elementGuidId>caa8dcb0-4537-4358-b914-3ad2469ae3aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='skipmaincontent']/div[3]/div/div/div/div/div[2]/ul/li/div/p[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.button_primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a2496b6c-30b1-4a15-b4fd-deac74ecde80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>See all everyday accounts</value>
      <webElementGuid>676a400d-56ca-41e0-b199-8ea22c83d1d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/banking/everyday-accounts.html?ei=prod_everyday-CTASeeAll</value>
      <webElementGuid>bd31721b-f0db-4486-8935-2bae0ffc496c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button_primary</value>
      <webElementGuid>c3c1d36c-7e3d-457d-aa4d-6814910f605f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracker-type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>587c4bea-413e-468a-9cce-dd2cffa086b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracker_ei</name>
      <type>Main</type>
      <value>default_0_1</value>
      <webElementGuid>f675b4bc-7bcd-450d-92cc-878d4adf1b8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracker-id</name>
      <type>Main</type>
      <value>default_0_1</value>
      <webElementGuid>964b804e-d8b4-42df-a97c-e44f2a1d0f1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>See all everyday accounts</value>
      <webElementGuid>b3601bf2-e6b9-4d89-8c2e-7508dca7dd3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;skipmaincontent&quot;)/div[@class=&quot;container content-container&quot;]/div[1]/div[@class=&quot;column&quot;]/div[@class=&quot;column-module bottom-divider&quot;]/div[@class=&quot;column-combo standard-spacing two-column&quot;]/div[@class=&quot;content-section&quot;]/ul[@class=&quot;item-section&quot;]/li[@class=&quot;item&quot;]/div[@class=&quot;item-inner&quot;]/p[@class=&quot;pt-2&quot;]/a[@class=&quot;button_primary&quot;]</value>
      <webElementGuid>be745373-52c5-426c-a34a-94f05838f915</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='skipmaincontent']/div[3]/div/div/div/div/div[2]/ul/li/div/p[2]/a</value>
      <webElementGuid>c3eea5f7-046b-4e03-b3dd-9233499dfcf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'See all everyday accounts')]</value>
      <webElementGuid>01784ff8-153c-4aff-81a7-bff1edce3082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Everyday accounts'])[1]/following::a[1]</value>
      <webElementGuid>29d6f106-c88b-4e45-b197-cac7d1f86c8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Our range of bank accounts'])[1]/following::a[1]</value>
      <webElementGuid>b7850ae6-4624-42f0-b3ee-332fe5bf501e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Savings accounts &amp; Term Deposits'])[1]/preceding::a[1]</value>
      <webElementGuid>59b72c23-272a-442d-b91b-2c5e6c75eb7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='See all savings options'])[1]/preceding::a[1]</value>
      <webElementGuid>3befcdb3-1946-4cac-abdd-6f521c525ce4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='See all everyday accounts']/parent::*</value>
      <webElementGuid>ecb3bb99-6ce4-4db8-ae3b-8292c84125b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/banking/everyday-accounts.html?ei=prod_everyday-CTASeeAll')]</value>
      <webElementGuid>d1abe4b5-60fc-4fbf-8614-52672d8dbc0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/a</value>
      <webElementGuid>137fb470-4c7f-4d2f-ab14-d5a14e489e63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/banking/everyday-accounts.html?ei=prod_everyday-CTASeeAll' and (text() = 'See all everyday accounts' or . = 'See all everyday accounts')]</value>
      <webElementGuid>5846d41d-3bd1-4c92-bd6e-e73663b63f83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
