<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Open now</name>
   <tag></tag>
   <elementGuidId>f3454555-61c2-4c46-b218-26127c9b80e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CB-BANKING-EA-BANNER']/div/div/div/div[2]/div/div[2]/p/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.button_primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5b61e62a-baa4-4232-98a0-8cfbb7667f5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Open a Smart Access account</value>
      <webElementGuid>df1580a7-3794-4c74-8f20-a4be6f774505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#banner_copy116801625461625459f1a3-545b-4bf8-8588-ce86f7320f2b</value>
      <webElementGuid>727526ab-94d2-4ccc-a6f1-d9af981666b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button_primary</value>
      <webElementGuid>7a0d7128-8ba8-4d6c-b27c-fc7dcb9c4c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>5d6ce77f-1683-4bfd-93a2-6657e221478c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracker-id</name>
      <type>Main</type>
      <value>default_0_1</value>
      <webElementGuid>1425d2c1-a004-450c-bb1a-1fab52c84dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracker-type</name>
      <type>Main</type>
      <value>launcherbuttonmodal</value>
      <webElementGuid>12306bfb-ba29-406e-8d01-e3cf180273c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracker_ei</name>
      <type>Main</type>
      <value>default_0_1</value>
      <webElementGuid>69a709f9-e2de-4d7f-a85b-3ee3f7bf6763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Open now</value>
      <webElementGuid>6ab1204d-3344-47d2-8b84-8fb6e2ee22e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CB-BANKING-EA-BANNER&quot;)/div[1]/div[@class=&quot;banner section&quot;]/div[@class=&quot;hero-banner-module&quot;]/div[@class=&quot;banner-content-panel&quot;]/div[@class=&quot;banner-content no-offer&quot;]/div[@class=&quot;cta&quot;]/p[1]/a[@class=&quot;button_primary&quot;]</value>
      <webElementGuid>4e74d676-b696-477c-8bf9-2ff832adf484</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CB-BANKING-EA-BANNER']/div/div/div/div[2]/div/div[2]/p/a</value>
      <webElementGuid>66be2dc7-9181-40a1-975e-df1067b3b669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Open now')]</value>
      <webElementGuid>19b8d6c9-3d2e-497b-bcc0-2c0d5e60763b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Everyday account for everyone'])[1]/following::a[2]</value>
      <webElementGuid>cea64a14-dd1f-4f07-ad3c-1d3c81f2c749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Everyday accounts'])[2]/following::a[2]</value>
      <webElementGuid>82293820-942f-4d1a-bf25-7e3b50b60b0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/preceding::a[1]</value>
      <webElementGuid>9c9ce200-8a9f-4202-b655-f968a90c8c63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Already a CommBank customer?'])[1]/preceding::a[1]</value>
      <webElementGuid>bc8a1aab-7c05-49c2-883e-319a6ff43c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Open now']/parent::*</value>
      <webElementGuid>0906d8dd-d921-4233-9d88-9ae7de23e325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#banner_copy116801625461625459f1a3-545b-4bf8-8588-ce86f7320f2b')]</value>
      <webElementGuid>514d28fb-7f02-47b2-86e7-fbbb2d0f0413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p/a</value>
      <webElementGuid>797a21db-f8e9-4495-a75a-92c739999b96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#banner_copy116801625461625459f1a3-545b-4bf8-8588-ce86f7320f2b' and (text() = 'Open now' or . = 'Open now')]</value>
      <webElementGuid>3695ef6b-3fd8-41d0-8e1a-153decd0e5a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
