<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Open now_1</name>
   <tag></tag>
   <elementGuidId>c1cdd576-a782-4cb0-ba99-ff1929ac024d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='banner_copy116801625461625459f1a3-545b-4bf8-8588-ce86f7320f2b']/div/div/div[2]/p/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.modal-body.standard-spacing.no-desc > p > a.button_primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7d35b9c8-4b27-464a-948c-cb20e94a357e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button_primary</value>
      <webElementGuid>bbbf1d4b-7486-4905-9c81-3ee9962f8693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Open now</value>
      <webElementGuid>9060e9b4-f91d-48cf-99b2-5501c2a1de8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.commbank.com.au/digital/eosmartaccess/ntb</value>
      <webElementGuid>27324aad-1ebd-4574-bfb7-9190f5121aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracker-product</name>
      <type>Main</type>
      <value>000684</value>
      <webElementGuid>161b068d-fd0b-4fa1-8232-c3a534a6fc2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracker-locationid</name>
      <type>Main</type>
      <value>cta-smartaccess-openntb</value>
      <webElementGuid>ef9f17a5-4452-4510-ad0c-943fabf2797e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracker-id</name>
      <type>Main</type>
      <value>default_0_1</value>
      <webElementGuid>06ad956f-6bc1-46b7-a623-a97e3f274f19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracker-type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b531af6b-6322-4cb8-a4e5-287b83f19485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracker_ei</name>
      <type>Main</type>
      <value>default_0_1</value>
      <webElementGuid>d16c383b-e727-4595-b30b-d282eb6fa875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>42f9b3e2-aaba-4f7b-823f-66c67293488c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Open now</value>
      <webElementGuid>fa9e12c3-17d8-494f-a9f6-c8ca07d30d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;banner_copy116801625461625459f1a3-545b-4bf8-8588-ce86f7320f2b&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body standard-spacing no-desc&quot;]/p[1]/a[@class=&quot;button_primary&quot;]</value>
      <webElementGuid>bc5be0d5-1133-4bcc-850b-bee5700db040</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='banner_copy116801625461625459f1a3-545b-4bf8-8588-ce86f7320f2b']/div/div/div[2]/p/a</value>
      <webElementGuid>97a9ee3d-49db-4892-b6de-0308765d366a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Open now')])[2]</value>
      <webElementGuid>237c07d5-9ed2-4bb5-adef-761c5f46bcf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New CommBank customer?'])[1]/following::a[1]</value>
      <webElementGuid>565588fe-6e59-477a-b10d-40bcd74a5cd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open in NetBank'])[1]/following::a[1]</value>
      <webElementGuid>6374edd9-a653-4a1a-b53b-f2fe6e15304a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Find out more'])[1]/preceding::a[1]</value>
      <webElementGuid>e28f8e4a-cae9-425a-a264-347a0f88543b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Other bank account options if you', &quot;'&quot;, 're:')])[1]/preceding::a[2]</value>
      <webElementGuid>1f9f577d-e2fb-48e8-aa6a-e85d717f29af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.commbank.com.au/digital/eosmartaccess/ntb')]</value>
      <webElementGuid>ff091920-b5bd-4ac2-a82d-d03e411070c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/p/a</value>
      <webElementGuid>cd87bfc1-0366-4abb-8d1e-a1e4ea753a12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.commbank.com.au/digital/eosmartaccess/ntb' and (text() = 'Open now' or . = 'Open now')]</value>
      <webElementGuid>ec563b5a-3186-4755-8cf5-2c35db0b9029</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
